markdown: redcarpet
highlighter: pygments
permalink: /posts/:title
rdiscount:
  extensions: [smart]
title: Brandon Williams
production_url : http://williamsbdev.com
disqus_shortname: williamsbdev
author:
  name: Brandon Williams
  github: williamsbdev
  twitter: williamsbdev
  email: williamsbdev@gmail.com
